#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PM100D功率计用户界面定义模块

该文件由PyQt5的UI代码生成器自动生成，定义了PM100D功率计控制程序的用户界面布局。
包含所有的界面控件、布局管理器和控件属性设置。

界面组件：
- 主窗口布局和标题栏
- 设备连接和端口选择面板
- 功率测量显示区域（LCD数字显示）
- 实时波形绘图区域
- 控制按钮组（连接、记录、设置等）
- 波长和补偿值设置控件
- 自动量程控制按钮

注意事项：
- 此文件由PyQt5 UI代码生成器自动生成
- 手动修改此文件的内容在重新生成时会丢失
- 如需修改界面，请编辑对应的.ui文件并重新生成
- 业务逻辑应在PM100D_Control.py中实现

生成信息：
- 源文件：PM100D_Control.ui
- 生成器：PyQt5 UI code generator 5.15.9

作者: ivan (界面设计)
创建时间: 2025
版本: v1.0.1
"""

# Form implementation generated from reading ui file 'PM100D_Control.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, Qt
from PyQt5.QtWidgets import QLabel


class ClickableLabel(QLabel):
    """
    可点击的标签控件
    
    继承自QLabel，添加了点击事件功能。主要用于版本标签的点击响应，
    点击后可以显示关于对话框。
    
    Signals:
        clicked: 鼠标点击信号
    """
    clicked = pyqtSignal()

    def __init__(self, parent=None):
        """
        初始化可点击标签
        
        Args:
            parent: 父控件
        """
        super(ClickableLabel, self).__init__(parent)

    def mousePressEvent(self, event):
        """
        鼠标按下事件处理
        
        当鼠标左键按下时发出clicked信号。
        
        Args:
            event: 鼠标事件对象
        """
        if event.button() == Qt.LeftButton:
            self.clicked.emit()
        super(ClickableLabel, self).mousePressEvent(event)


class Ui_MainWindow(object):
    """
    主窗口用户界面类
    
    定义了PM100D功率计控制程序的完整用户界面布局和控件配置。
    包含所有界面元素的创建、布局设置和属性配置。
    """
    
    def setupUi(self, MainWindow):
        """
        设置用户界面
        
        创建并配置主窗口的所有界面控件，包括布局管理器、
        控件属性、字体设置等。
        
        Args:
            MainWindow: 主窗口对象
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 820)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setColumnStretch(0, 0)
        self.gridLayout.setColumnStretch(2, 1)

        # ── 标题栏 ──
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setObjectName("title")
        self.horizontalLayout_9.addWidget(self.title)
        self.version = ClickableLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.version.setFont(font)
        self.version.setText("")
        self.version.setObjectName("version")
        self.horizontalLayout_9.addWidget(self.version)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_9, 0, 0, 1, 3)

        # ── 左侧：串口连接面板（加宽） ──
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 1, 1, 1)

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumWidth(320)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumWidth(40)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Com = QtWidgets.QComboBox(self.tab)
        self.Com.setMinimumWidth(220)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.Com.setSizePolicy(sizePolicy)
        self.Com.setObjectName("Com")
        self.horizontalLayout_2.addWidget(self.Com)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.ComName = QtWidgets.QLabel(self.tab)
        self.ComName.setWordWrap(True)
        self.ComName.setText("")
        self.ComName.setObjectName("ComName")
        self.verticalLayout_2.addWidget(self.ComName)
        self.ComCheck = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.ComCheck.setFont(font)
        self.ComCheck.setObjectName("ComCheck")
        self.verticalLayout_2.addWidget(self.ComCheck)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        portInfoLabel = QtWidgets.QLabel(self.tab)
        portInfoLabel.setText("操作详情")
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        portInfoLabel.setFont(font)
        self.verticalLayout_2.addWidget(portInfoLabel)
        self.portInfo = QtWidgets.QTextBrowser(self.tab)
        self.portInfo.setMinimumHeight(200)
        self.portInfo.setSizePolicy(
            QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        )
        self.portInfo.setObjectName("portInfo")
        self.verticalLayout_2.addWidget(self.portInfo, 1)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)

        # ── 右侧：测量与控制区域 ──
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")

        # 通道标题
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setMaximumHeight(36)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)

        # 设备状态分组
        self.statusGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.statusGroupBox.setObjectName("statusGroupBox")
        self.formLayout_status = QtWidgets.QFormLayout(self.statusGroupBox)
        self.formLayout_status.setLabelAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.formLayout_status.setHorizontalSpacing(16)
        self.formLayout_status.setVerticalSpacing(8)
        self.formLayout_status.setObjectName("formLayout_status")
        self.CH1_wave = QtWidgets.QLabel(self.statusGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CH1_wave.setFont(font)
        self.CH1_wave.setObjectName("CH1_wave")
        self.formLayout_status.addRow("波长：", self.CH1_wave)
        self.CH1_comp_2 = QtWidgets.QLabel(self.statusGroupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1_comp_2.setFont(font)
        self.CH1_comp_2.setObjectName("CH1_comp_2")
        self.formLayout_status.addRow("补偿值：", self.CH1_comp_2)
        self.CH1_unit = QtWidgets.QLabel(self.statusGroupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1_unit.setFont(font)
        self.CH1_unit.setObjectName("CH1_unit")
        self.formLayout_status.addRow("功率单位：", self.CH1_unit)
        self.CH1_range = QtWidgets.QLabel(self.statusGroupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1_range.setFont(font)
        self.CH1_range.setObjectName("CH1_range")
        self.formLayout_status.addRow("自动范围：", self.CH1_range)
        self.verticalLayout.addWidget(self.statusGroupBox)

        # 功率显示区域
        self.measureHBox = QtWidgets.QHBoxLayout()
        self.measureHBox.setSpacing(24)
        self.measureHBox.setObjectName("measureHBox")

        self.mainMeasureVBox = QtWidgets.QVBoxLayout()
        self.mainMeasureVBox.setObjectName("mainMeasureVBox")
        mainLabel = QtWidgets.QLabel(self.centralwidget)
        mainLabel.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        mainLabel.setFont(font)
        mainLabel.setText("当前功率")
        self.mainMeasureVBox.addWidget(mainLabel)
        self.CH1_Value = QtWidgets.QLCDNumber(self.centralwidget)
        self.CH1_Value.setMinimumSize(QtCore.QSize(300, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.CH1_Value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.CH1_Value.setFont(font)
        self.CH1_Value.setStyleSheet("")
        self.CH1_Value.setFrameShape(QtWidgets.QFrame.Box)
        self.CH1_Value.setMidLineWidth(0)
        self.CH1_Value.setSmallDecimalPoint(False)
        self.CH1_Value.setDigitCount(9)
        self.CH1_Value.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CH1_Value.setProperty("value", 0.0)
        self.CH1_Value.setObjectName("CH1_Value")
        self.mainMeasureVBox.addWidget(self.CH1_Value)
        self.measureHBox.addLayout(self.mainMeasureVBox, 3)

        self.maxMeasureVBox = QtWidgets.QVBoxLayout()
        self.maxMeasureVBox.setObjectName("maxMeasureVBox")
        self.CH1_2 = QtWidgets.QLabel(self.centralwidget)
        self.CH1_2.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.CH1_2.setFont(font)
        self.CH1_2.setObjectName("CH1_2")
        self.maxMeasureVBox.addWidget(self.CH1_2)
        self.CH1_max = QtWidgets.QLCDNumber(self.centralwidget)
        self.CH1_max.setMinimumSize(QtCore.QSize(220, 90))
        self.CH1_max.setDigitCount(9)
        self.CH1_max.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CH1_max.setObjectName("CH1_max")
        self.maxMeasureVBox.addWidget(self.CH1_max)
        self.measureHBox.addLayout(self.maxMeasureVBox, 2)

        self.minMeasureVBox = QtWidgets.QVBoxLayout()
        self.minMeasureVBox.setObjectName("minMeasureVBox")
        self.CH1_3 = QtWidgets.QLabel(self.centralwidget)
        self.CH1_3.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.CH1_3.setFont(font)
        self.CH1_3.setObjectName("CH1_3")
        self.minMeasureVBox.addWidget(self.CH1_3)
        self.CH1_min = QtWidgets.QLCDNumber(self.centralwidget)
        self.CH1_min.setMinimumSize(QtCore.QSize(220, 90))
        self.CH1_min.setDigitCount(9)
        self.CH1_min.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CH1_min.setObjectName("CH1_min")
        self.minMeasureVBox.addWidget(self.CH1_min)
        self.measureHBox.addLayout(self.minMeasureVBox, 2)
        self.verticalLayout.addLayout(self.measureHBox)

        # 参数设置分组
        self.settingsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.settingsGroupBox.setObjectName("settingsGroupBox")
        self.formLayout_settings = QtWidgets.QFormLayout(self.settingsGroupBox)
        self.formLayout_settings.setLabelAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.formLayout_settings.setHorizontalSpacing(12)
        self.formLayout_settings.setVerticalSpacing(10)
        self.formLayout_settings.setObjectName("formLayout_settings")

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CH1_comp = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.CH1_comp.setMinimumWidth(100)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1_comp.setFont(font)
        self.CH1_comp.setObjectName("CH1_comp")
        self.horizontalLayout_4.addWidget(self.CH1_comp)
        self.CH1_comp_unit = QtWidgets.QLabel(self.settingsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.CH1_comp_unit.setFont(font)
        self.CH1_comp_unit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CH1_comp_unit.setMinimumWidth(30)
        self.CH1_comp_unit.setObjectName("CH1_comp_unit")
        self.horizontalLayout_4.addWidget(self.CH1_comp_unit)
        self.setCH1comp = QtWidgets.QPushButton(self.settingsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.setCH1comp.setFont(font)
        self.setCH1comp.setMinimumWidth(70)
        self.setCH1comp.setObjectName("setCH1comp")
        self.horizontalLayout_4.addWidget(self.setCH1comp)
        self.CH1_comp_set = QtWidgets.QLabel(self.settingsGroupBox)
        self.CH1_comp_set.setVisible(False)
        self.CH1_comp_set.setObjectName("CH1_comp_set")
        self.formLayout_settings.addRow("补偿设置：", self.horizontalLayout_4)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CH1Twave = QtWidgets.QComboBox(self.settingsGroupBox)
        self.CH1Twave.setMinimumWidth(140)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1Twave.setFont(font)
        self.CH1Twave.setEditable(True)
        self.CH1Twave.setObjectName("CH1Twave")
        self.CH1Twave.addItem("")
        self.CH1Twave.addItem("")
        self.CH1Twave.addItem("")
        self.CH1Twave.addItem("")
        self.CH1Twave.addItem("")
        self.CH1Twave.addItem("")
        self.horizontalLayout.addWidget(self.CH1Twave)
        self.setCH1wave = QtWidgets.QPushButton(self.settingsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.setCH1wave.setFont(font)
        self.setCH1wave.setMinimumWidth(70)
        self.setCH1wave.setObjectName("setCH1wave")
        self.horizontalLayout.addWidget(self.setCH1wave)
        self.CH1_wave_set = QtWidgets.QLabel(self.settingsGroupBox)
        self.CH1_wave_set.setVisible(False)
        self.CH1_wave_set.setObjectName("CH1_wave_set")
        self.formLayout_settings.addRow("波长设置：", self.horizontalLayout)

        self.horizontalLayout_unit = QtWidgets.QHBoxLayout()
        self.horizontalLayout_unit.setObjectName("horizontalLayout_unit")
        self.CH1TUnit = QtWidgets.QComboBox(self.settingsGroupBox)
        self.CH1TUnit.setMinimumWidth(100)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1TUnit.setFont(font)
        self.CH1TUnit.setObjectName("CH1TUnit")
        self.CH1TUnit.addItem("")
        self.CH1TUnit.addItem("")
        self.horizontalLayout_unit.addWidget(self.CH1TUnit)
        self.setCH1unit = QtWidgets.QPushButton(self.settingsGroupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.setCH1unit.setFont(font)
        self.setCH1unit.setMinimumWidth(70)
        self.setCH1unit.setObjectName("setCH1unit")
        self.horizontalLayout_unit.addWidget(self.setCH1unit)
        self.CH1_unit_set = QtWidgets.QLabel(self.settingsGroupBox)
        self.CH1_unit_set.setVisible(False)
        self.CH1_unit_set.setObjectName("CH1_unit_set")
        self.formLayout_settings.addRow("单位设置：", self.horizontalLayout_unit)

        self.verticalLayout.addWidget(self.settingsGroupBox)

        # 波形图
        self.CH1_Plot_layout = QtWidgets.QVBoxLayout()
        self.CH1_Plot_layout.setObjectName("CH1_Plot_layout")
        self.verticalLayout.addLayout(self.CH1_Plot_layout, 1)

        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)

        # 底部操作按钮
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Connect = QtWidgets.QPushButton(self.centralwidget)
        self.Connect.setMinimumHeight(32)
        self.Connect.setObjectName("Connect")
        self.horizontalLayout_3.addWidget(self.Connect)
        self.startRecordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startRecordBtn.setMinimumHeight(32)
        self.startRecordBtn.setObjectName("startRecordBtn")
        self.horizontalLayout_3.addWidget(self.startRecordBtn)
        self.stopRecordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopRecordBtn.setMinimumHeight(32)
        self.stopRecordBtn.setObjectName("stopRecordBtn")
        self.horizontalLayout_3.addWidget(self.stopRecordBtn)
        self.Disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.Disconnect.setMinimumHeight(32)
        self.Disconnect.setObjectName("Disconnect")
        self.horizontalLayout_3.addWidget(self.Disconnect)
        self.Clean = QtWidgets.QPushButton(self.centralwidget)
        self.Clean.setMinimumHeight(32)
        self.Clean.setObjectName("Clean")
        self.horizontalLayout_3.addWidget(self.Clean)
        self.enableAutoRange = QtWidgets.QPushButton(self.centralwidget)
        self.enableAutoRange.setMinimumHeight(32)
        self.enableAutoRange.setObjectName("enableAutoRange")
        self.horizontalLayout_3.addWidget(self.enableAutoRange)
        self.disableAutoRange = QtWidgets.QPushButton(self.centralwidget)
        self.disableAutoRange.setMinimumHeight(32)
        self.disableAutoRange.setObjectName("disableAutoRange")
        self.horizontalLayout_3.addWidget(self.disableAutoRange)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PM100D功率计控制台"))
        self.title.setText(_translate("MainWindow", "索雷伯PM100D功率计"))
        self.label.setText(_translate("MainWindow", "串口设置"))
        self.label_2.setText(_translate("MainWindow", "设备"))
        self.ComCheck.setText(_translate("MainWindow", "检查串口"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "串口"))
        self.statusGroupBox.setTitle(_translate("MainWindow", "设备状态"))
        self.settingsGroupBox.setTitle(_translate("MainWindow", "参数设置"))
        self.CH1_wave.setText(_translate("MainWindow", "未知"))
        self.CH1_comp_2.setText(_translate("MainWindow", "未知"))
        self.CH1_unit.setText(_translate("MainWindow", "未知"))
        self.CH1_range.setText(_translate("MainWindow", "关闭"))
        self.CH1_2.setText(_translate("MainWindow", "最大值"))
        self.CH1_3.setText(_translate("MainWindow", "最小值"))
        self.lineEdit.setText(_translate("MainWindow", "通道 1"))
        self.CH1_comp_set.setText(_translate("MainWindow", "补偿设置"))
        self.CH1_comp.setText(_translate("MainWindow", "0.02"))
        self.CH1_comp_unit.setText(_translate("MainWindow", "mW"))
        self.setCH1comp.setText(_translate("MainWindow", "设置"))
        self.CH1_wave_set.setText(_translate("MainWindow", "波长设置"))
        self.CH1Twave.setItemText(0, _translate("MainWindow", "1550nm"))
        self.CH1Twave.setItemText(1, _translate("MainWindow", "850nm"))
        self.CH1Twave.setItemText(2, _translate("MainWindow", "1300nm"))
        self.CH1Twave.setItemText(3, _translate("MainWindow", "1310nm"))
        self.CH1Twave.setItemText(4, _translate("MainWindow", "1490nm"))
        self.CH1Twave.setItemText(5, _translate("MainWindow", "1625nm"))
        self.setCH1wave.setText(_translate("MainWindow", "设置"))
        self.CH1_unit_set.setText(_translate("MainWindow", "单位设置"))
        self.CH1TUnit.setItemText(0, _translate("MainWindow", "W"))
        self.CH1TUnit.setItemText(1, _translate("MainWindow", "DBM"))
        self.setCH1unit.setText(_translate("MainWindow", "设置"))
        self.Connect.setText(_translate("MainWindow", "链接功率计"))
        self.startRecordBtn.setText(_translate("MainWindow", "开始记录"))
        self.stopRecordBtn.setText(_translate("MainWindow", "停止记录"))
        self.Disconnect.setText(_translate("MainWindow", "断开功率计"))
        self.Clean.setText(_translate("MainWindow", "清空"))
        self.enableAutoRange.setText(_translate("MainWindow", "开启自动范围"))
        self.disableAutoRange.setText(_translate("MainWindow", "关闭自动范围"))
