#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PM100D功率计用户界面定义模块

该文件由PyQt5的UI代码生成器自动生成，定义了PM100D功率计控制程序的用户界面布局。
包含所有的界面控件、布局管理器和控件属性设置。

界面组件：
- 主窗口布局和标题栏
- 设备连接和端口选择面板
- 功率测量显示区域（LCD数字显示）
- 实时波形绘图区域
- 控制按钮组（连接、记录、设置等）
- 波长和补偿值设置控件
- 自动量程控制按钮

注意事项：
- 此文件由PyQt5 UI代码生成器自动生成
- 手动修改此文件的内容在重新生成时会丢失
- 如需修改界面，请编辑对应的.ui文件并重新生成
- 业务逻辑应在PM100D_Control.py中实现

生成信息：
- 源文件：PM100D_Control.ui
- 生成器：PyQt5 UI code generator 5.15.9

作者: ivan (界面设计)
创建时间: 2025
版本: v1.0.1
"""

# Form implementation generated from reading ui file 'PM100D_Control.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, Qt
from PyQt5.QtWidgets import QLabel


class ClickableLabel(QLabel):
    """
    可点击的标签控件
    
    继承自QLabel，添加了点击事件功能。主要用于版本标签的点击响应，
    点击后可以显示关于对话框。
    
    Signals:
        clicked: 鼠标点击信号
    """
    clicked = pyqtSignal()

    def __init__(self, parent=None):
        """
        初始化可点击标签
        
        Args:
            parent: 父控件
        """
        super(ClickableLabel, self).__init__(parent)

    def mousePressEvent(self, event):
        """
        鼠标按下事件处理
        
        当鼠标左键按下时发出clicked信号。
        
        Args:
            event: 鼠标事件对象
        """
        if event.button() == Qt.LeftButton:
            self.clicked.emit()
        super(ClickableLabel, self).mousePressEvent(event)


class Ui_MainWindow(object):
    """
    主窗口用户界面类
    
    定义了PM100D功率计控制程序的完整用户界面布局和控件配置。
    包含所有界面元素的创建、布局设置和属性配置。
    """
    
    def setupUi(self, MainWindow):
        """
        设置用户界面
        
        创建并配置主窗口的所有界面控件，包括布局管理器、
        控件属性、字体设置等。
        
        Args:
            MainWindow: 主窗口对象
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1469, 773)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setObjectName("title")
        self.horizontalLayout_9.addWidget(self.title)
        self.version = ClickableLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.version.setFont(font)
        self.version.setText("")
        self.version.setObjectName("version")
        self.horizontalLayout_9.addWidget(self.version)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_9, 0, 0, 1, 3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Com = QtWidgets.QComboBox(self.tab)
        self.Com.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Com.setObjectName("Com")
        self.horizontalLayout_2.addWidget(self.Com)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.ComName = QtWidgets.QLabel(self.tab)
        self.ComName.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ComName.setText("")
        self.ComName.setObjectName("ComName")
        self.verticalLayout_2.addWidget(self.ComName)
        self.ComCheck = QtWidgets.QPushButton(self.tab)
        self.ComCheck.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.ComCheck.setFont(font)
        self.ComCheck.setObjectName("ComCheck")
        self.verticalLayout_2.addWidget(self.ComCheck)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.portInfo = QtWidgets.QTextBrowser(self.tab)
        self.portInfo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.portInfo.setObjectName("portInfo")
        self.verticalLayout_2.addWidget(self.portInfo)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(33)
        self.gridLayout_2.setVerticalSpacing(56)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CH1_min = QtWidgets.QLCDNumber(self.centralwidget)
        self.CH1_min.setMinimumSize(QtCore.QSize(200, 100))
        self.CH1_min.setDigitCount(7)
        self.CH1_min.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CH1_min.setObjectName("CH1_min")
        self.gridLayout_2.addWidget(self.CH1_min, 0, 6, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.CH1_wave = QtWidgets.QLabel(self.centralwidget)
        self.CH1_wave.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CH1_wave.setFont(font)
        self.CH1_wave.setObjectName("CH1_wave")
        self.verticalLayout_5.addWidget(self.CH1_wave)
        self.CH1_comp_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1_comp_2.setFont(font)
        self.CH1_comp_2.setObjectName("CH1_comp_2")
        self.verticalLayout_5.addWidget(self.CH1_comp_2)
        self.CH1_unit = QtWidgets.QLabel(self.centralwidget)
        self.CH1_unit.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1_unit.setFont(font)
        self.CH1_unit.setObjectName("CH1_unit")
        self.verticalLayout_5.addWidget(self.CH1_unit)
        self.CH1_range = QtWidgets.QLabel(self.centralwidget)
        self.CH1_range.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1_range.setFont(font)
        self.CH1_range.setObjectName("CH1_range")
        self.verticalLayout_5.addWidget(self.CH1_range)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.CH1_2 = QtWidgets.QLabel(self.centralwidget)
        self.CH1_2.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.CH1_2.setFont(font)
        self.CH1_2.setObjectName("CH1_2")
        self.gridLayout_2.addWidget(self.CH1_2, 0, 3, 1, 1)
        self.CH1_max = QtWidgets.QLCDNumber(self.centralwidget)
        self.CH1_max.setMinimumSize(QtCore.QSize(200, 100))
        self.CH1_max.setDigitCount(7)
        self.CH1_max.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CH1_max.setObjectName("CH1_max")
        self.gridLayout_2.addWidget(self.CH1_max, 0, 4, 1, 1)
        self.CH1_3 = QtWidgets.QLabel(self.centralwidget)
        self.CH1_3.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.CH1_3.setFont(font)
        self.CH1_3.setObjectName("CH1_3")
        self.gridLayout_2.addWidget(self.CH1_3, 0, 5, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 4, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CH1_comp_set = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1_comp_set.setFont(font)
        self.CH1_comp_set.setObjectName("CH1_comp_set")
        self.horizontalLayout_4.addWidget(self.CH1_comp_set)
        self.CH1_comp = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CH1_comp.sizePolicy().hasHeightForWidth())
        self.CH1_comp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1_comp.setFont(font)
        self.CH1_comp.setObjectName("CH1_comp")
        self.horizontalLayout_4.addWidget(self.CH1_comp)
        self.CH1_comp_unit = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.CH1_comp_unit.setFont(font)
        self.CH1_comp_unit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CH1_comp_unit.setObjectName("CH1_comp_unit")
        self.horizontalLayout_4.addWidget(self.CH1_comp_unit)
        self.setCH1comp = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.setCH1comp.setFont(font)
        self.setCH1comp.setObjectName("setCH1comp")
        self.horizontalLayout_4.addWidget(self.setCH1comp)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.CH1_Value = QtWidgets.QLCDNumber(self.centralwidget)
        self.CH1_Value.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.CH1_Value.setFont(font)
        self.CH1_Value.setStyleSheet("")
        self.CH1_Value.setFrameShape(QtWidgets.QFrame.Box)
        self.CH1_Value.setMidLineWidth(0)
        self.CH1_Value.setSmallDecimalPoint(False)
        self.CH1_Value.setDigitCount(7)
        self.CH1_Value.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CH1_Value.setProperty("value", 0.0)
        self.CH1_Value.setObjectName("CH1_Value")
        self.gridLayout_2.addWidget(self.CH1_Value, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CH1_wave_set = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1_wave_set.setFont(font)
        self.CH1_wave_set.setObjectName("CH1_wave_set")
        self.horizontalLayout.addWidget(self.CH1_wave_set)
        self.CH1Twave = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1Twave.setFont(font)
        self.CH1Twave.setEditable(True)
        self.CH1Twave.setObjectName("CH1Twave")
        self.CH1Twave.addItem("")
        self.CH1Twave.addItem("")
        self.CH1Twave.addItem("")
        self.CH1Twave.addItem("")
        self.CH1Twave.addItem("")
        self.CH1Twave.addItem("")
        self.horizontalLayout.addWidget(self.CH1Twave)
        self.setCH1wave = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.setCH1wave.setFont(font)
        self.setCH1wave.setObjectName("setCH1wave")
        self.horizontalLayout.addWidget(self.setCH1wave)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.horizontalLayout_unit = QtWidgets.QHBoxLayout()
        self.horizontalLayout_unit.setObjectName("horizontalLayout_unit")
        self.CH1_unit_set = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1_unit_set.setFont(font)
        self.CH1_unit_set.setObjectName("CH1_unit_set")
        self.horizontalLayout_unit.addWidget(self.CH1_unit_set)
        self.CH1TUnit = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.CH1TUnit.setFont(font)
        self.CH1TUnit.setObjectName("CH1TUnit")
        self.CH1TUnit.addItem("")
        self.CH1TUnit.addItem("")
        self.horizontalLayout_unit.addWidget(self.CH1TUnit)
        self.setCH1unit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.setCH1unit.setFont(font)
        self.setCH1unit.setObjectName("setCH1unit")
        self.horizontalLayout_unit.addWidget(self.setCH1unit)
        self.gridLayout_2.addLayout(self.horizontalLayout_unit, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.CH1_Plot_layout = QtWidgets.QVBoxLayout()
        self.CH1_Plot_layout.setObjectName("CH1_Plot_layout")
        self.verticalLayout.addLayout(self.CH1_Plot_layout)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Connect = QtWidgets.QPushButton(self.centralwidget)
        self.Connect.setObjectName("Connect")
        self.horizontalLayout_3.addWidget(self.Connect)
        self.startRecordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startRecordBtn.setObjectName("startRecordBtn")
        self.horizontalLayout_3.addWidget(self.startRecordBtn)
        self.stopRecordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopRecordBtn.setObjectName("stopRecordBtn")
        self.horizontalLayout_3.addWidget(self.stopRecordBtn)
        self.Disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.Disconnect.setObjectName("Disconnect")
        self.horizontalLayout_3.addWidget(self.Disconnect)
        self.Clean = QtWidgets.QPushButton(self.centralwidget)
        self.Clean.setObjectName("Clean")
        self.horizontalLayout_3.addWidget(self.Clean)
        self.enableAutoRange = QtWidgets.QPushButton(self.centralwidget)
        self.enableAutoRange.setObjectName("enableAutoRange")
        self.horizontalLayout_3.addWidget(self.enableAutoRange)
        self.disableAutoRange = QtWidgets.QPushButton(self.centralwidget)
        self.disableAutoRange.setObjectName("disableAutoRange")
        self.horizontalLayout_3.addWidget(self.disableAutoRange)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PM100D功率计控制台"))
        self.title.setText(_translate("MainWindow", "索雷伯PM100D功率计"))
        self.label.setText(_translate("MainWindow", "串口设置"))
        self.label_2.setText(_translate("MainWindow", "设备"))
        self.ComCheck.setText(_translate("MainWindow", "检查串口"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "串口"))
        self.CH1_wave.setText(_translate("MainWindow", "波长值：未知"))
        self.CH1_comp_2.setText(_translate("MainWindow", "补偿值：未知"))
        self.CH1_unit.setText(_translate("MainWindow", "功率单位：未知"))
        self.CH1_range.setText(_translate("MainWindow", "自动范围：关闭"))
        self.CH1_2.setText(_translate("MainWindow", "最大值"))
        self.CH1_3.setText(_translate("MainWindow", "最小值"))
        self.lineEdit.setText(_translate("MainWindow", "通道1"))
        self.CH1_comp_set.setText(_translate("MainWindow", "补偿设置"))
        self.CH1_comp.setText(_translate("MainWindow", "0.02"))
        self.CH1_comp_unit.setText(_translate("MainWindow", "mW"))
        self.setCH1comp.setText(_translate("MainWindow", "设置"))
        self.CH1_wave_set.setText(_translate("MainWindow", "波长设置"))
        self.CH1Twave.setItemText(0, _translate("MainWindow", "1550nm"))
        self.CH1Twave.setItemText(1, _translate("MainWindow", "850nm"))
        self.CH1Twave.setItemText(2, _translate("MainWindow", "1300nm"))
        self.CH1Twave.setItemText(3, _translate("MainWindow", "1310nm"))
        self.CH1Twave.setItemText(4, _translate("MainWindow", "1490nm"))
        self.CH1Twave.setItemText(5, _translate("MainWindow", "1625nm"))
        self.setCH1wave.setText(_translate("MainWindow", "设置"))
        self.CH1_unit_set.setText(_translate("MainWindow", "单位设置"))
        self.CH1TUnit.setItemText(0, _translate("MainWindow", "W"))
        self.CH1TUnit.setItemText(1, _translate("MainWindow", "DBM"))
        self.setCH1unit.setText(_translate("MainWindow", "设置"))
        self.Connect.setText(_translate("MainWindow", "链接功率计"))
        self.startRecordBtn.setText(_translate("MainWindow", "开始记录"))
        self.stopRecordBtn.setText(_translate("MainWindow", "停止记录"))
        self.Disconnect.setText(_translate("MainWindow", "断开功率计"))
        self.Clean.setText(_translate("MainWindow", "清空"))
        self.enableAutoRange.setText(_translate("MainWindow", "开启自动范围"))
        self.disableAutoRange.setText(_translate("MainWindow", "关闭自动范围"))
